import { withVueTs, vueTsConfigs } from '@vue/eslint-config-typescript';
import skipFormatting from '@vue/eslint-config-prettier/skip-formatting';
import pluginVue from 'eslint-plugin-vue';

export default withVueTs(
  {
    name: 'odin/ignores',
    ignores: [
      'dist/**',
      'android/**',
      'ios/**',
      'design_reference/**',
      'design_exploration/**',
      'character_designs/**',
      'new_designs/**',
      'copilot/**',
      'docs/**',
      // Generated by drizzle-kit (npm run db:generate); not hand-maintained.
      'src/db/migrations/**',
    ],
  },
  pluginVue.configs['flat/recommended'],
  vueTsConfigs.recommended,
  skipFormatting,
  {
    // STYLEGUIDE section 10: useViewport() is the only file allowed to read
    // window dimensions or media queries. Everything else must consume it.
    name: 'odin/viewport-single-door',
    rules: {
      'no-restricted-globals': [
        'error',
        {
          name: 'innerWidth',
          message: 'Read viewport size through composables/useViewport.ts only.',
        },
        {
          name: 'innerHeight',
          message: 'Read viewport size through composables/useViewport.ts only.',
        },
        {
          name: 'matchMedia',
          message: 'Media queries in JS go through composables/useViewport.ts only.',
        },
      ],
      'no-restricted-properties': [
        'error',
        {
          object: 'window',
          property: 'innerWidth',
          message: 'Read viewport size through composables/useViewport.ts only.',
        },
        {
          object: 'window',
          property: 'innerHeight',
          message: 'Read viewport size through composables/useViewport.ts only.',
        },
        {
          object: 'window',
          property: 'matchMedia',
          message: 'Media queries in JS go through composables/useViewport.ts only.',
        },
      ],
    },
  },
  {
    name: 'odin/viewport-single-door-carveout',
    files: ['src/composables/useViewport.ts'],
    rules: {
      'no-restricted-globals': 'off',
      'no-restricted-properties': 'off',
    },
  },
  {
    // Bridge isolation, second enforcer: dependency-cruiser (.dependency-cruiser.json)
    // already catches this, including inside .vue SFCs. This one exists for
    // failure distance, not coverage - it fires at editor/save time, before
    // depcruise ever runs. Scoped to src/ so capacitor.config.ts stays legal.
    name: 'odin/bridge-isolation',
    files: ['src/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@capacitor/*', '@capacitor-community/*'],
              message: 'Only src/native/ may import Capacitor plugins (bridge isolation).',
            },
          ],
        },
      ],
    },
  },
  {
    name: 'odin/bridge-isolation-carveout',
    files: ['src/native/**'],
    rules: {
      'no-restricted-imports': 'off',
    },
  },
  {
    // The device SQLite plugin cannot execute RETURNING: it fakes it by
    // re-querying with the statement's extracted WHERE text and an empty
    // bind list, silently returning wrong rows (verified in plugin 8.1.0
    // Android + iOS sources; see src/db/proxy-statements.ts). Both drivers
    // also reject row-returning writes at runtime; this rule moves the
    // failure to save time.
    name: 'odin/no-returning',
    files: ['src/**'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: 'CallExpression[callee.property.name="returning"]',
          message:
            '.returning() is broken on the device SQLite plugin; ' +
            'use separate read/write statements in a transaction instead ' +
            '(see src/db/proxy-statements.ts).',
        },
      ],
    },
  },
);
