import { withVueTs, vueTsConfigs } from '@vue/eslint-config-typescript';
import skipFormatting from '@vue/eslint-config-prettier/skip-formatting';
import pluginVue from 'eslint-plugin-vue';

// Shared between the src-wide wall and the ids.ts carve-out below, which
// lifts only the crypto selectors: a flat-config block REPLACES a rule id
// wholesale, so the carve-out must restate every ban it keeps.
const returningBan = {
  selector: 'CallExpression[callee.property.name="returning"]',
  message:
    '.returning() is broken on the device SQLite plugin; ' +
    'use separate read/write statements in a transaction instead ' +
    '(see src/db/proxy-statements.ts).',
};

export default withVueTs(
  {
    name: 'odin/ignores',
    ignores: [
      'dist/**',
      'android/**',
      'ios/**',
      'design_reference/**',
      'design_exploration/**',
      'character_designs/**',
      'new_designs/**',
      'copilot/**',
      // Feature working notes (git-ignored), including vendored
      // design-previewer tooling; .claude/CLAUDE.md itself stays linted.
      '.claude/features/**',
      'docs/**',
      // Generated by drizzle-kit (npm run db:generate); not hand-maintained.
      'src/db/migrations/**',
    ],
  },
  pluginVue.configs['flat/recommended'],
  vueTsConfigs.recommended,
  skipFormatting,
  {
    // useViewport() is the only file allowed to read window dimensions
    // or media queries. Everything else must consume it.
    name: 'odin/viewport-single-door',
    rules: {
      'no-restricted-globals': [
        'error',
        {
          name: 'innerWidth',
          message: 'Read viewport size through composables/useViewport.ts only.',
        },
        {
          name: 'innerHeight',
          message: 'Read viewport size through composables/useViewport.ts only.',
        },
        {
          name: 'matchMedia',
          message: 'Media queries in JS go through composables/useViewport.ts only.',
        },
      ],
      'no-restricted-properties': [
        'error',
        {
          object: 'window',
          property: 'innerWidth',
          message: 'Read viewport size through composables/useViewport.ts only.',
        },
        {
          object: 'window',
          property: 'innerHeight',
          message: 'Read viewport size through composables/useViewport.ts only.',
        },
        {
          object: 'window',
          property: 'matchMedia',
          message: 'Media queries in JS go through composables/useViewport.ts only.',
        },
      ],
    },
  },
  {
    name: 'odin/viewport-single-door-carveout',
    files: ['src/composables/useViewport.ts'],
    rules: {
      'no-restricted-globals': 'off',
      'no-restricted-properties': 'off',
    },
  },
  {
    // Bridge isolation, second enforcer: dependency-cruiser (.dependency-cruiser.json)
    // already catches this, including inside .vue SFCs. This one exists for
    // failure distance, not coverage - it fires at editor/save time, before
    // depcruise ever runs. Scoped to src/ so capacitor.config.ts stays legal.
    name: 'odin/bridge-isolation',
    files: ['src/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@capacitor/*', '@capacitor-community/*'],
              message: 'Only src/native/ may import Capacitor plugins (bridge isolation).',
            },
          ],
        },
      ],
    },
  },
  {
    name: 'odin/bridge-isolation-carveout',
    files: ['src/native/**'],
    rules: {
      'no-restricted-imports': 'off',
    },
  },
  {
    // Banned APIs, enforced at save time (one block: flat config replaces,
    // not merges, a rule id across blocks, so every no-restricted-syntax
    // entry for src/** must live together).
    //
    // .returning(): the device SQLite plugin cannot execute RETURNING - it
    // fakes it by re-querying with the statement's extracted WHERE text and
    // an empty bind list, silently returning wrong rows (verified in plugin
    // 8.1.0 Android + iOS sources; see src/db/proxy-statements.ts). Both
    // drivers also reject row-returning writes at runtime.
    //
    // crypto.randomUUID / crypto.subtle: secure-context-only. They exist
    // in Node tests and installed builds but are undefined when the
    // WebView loads from the LAN dev server (http://<ip>:5173), so the
    // wall stays green while dev:phone breaks at runtime.
    name: 'odin/banned-apis',
    files: ['src/**'],
    rules: {
      'no-restricted-syntax': [
        'error',
        returningBan,
        {
          selector: 'MemberExpression[object.name="crypto"][property.name="randomUUID"]',
          message:
            'crypto.randomUUID is secure-context-only and undefined in the ' +
            'phone dev loop (http origin); use newId() from db/ids.ts.',
        },
        {
          selector: 'MemberExpression[object.name="crypto"][property.name="subtle"]',
          message:
            'crypto.subtle is secure-context-only and undefined in the ' +
            'phone dev loop (http origin); it cannot be relied on here.',
        },
      ],
    },
  },
  {
    // ids.ts IS the sanctioned wrapper: it feature-detects randomUUID and
    // carries the insecure-context fallback. Only the crypto selectors
    // are lifted - the .returning() ban stays live, so a query sneaking
    // into ids.ts still hits the plugin-defect wall.
    name: 'odin/banned-apis-carveout',
    files: ['src/db/ids.ts'],
    rules: {
      'no-restricted-syntax': ['error', returningBan],
    },
  },
);
